### ISSUE TITLE
Rabbit Submitter is not using Publisher Confirms

### ISSUE THREAD

**Issue by JamesGardiner** [ONSdigital/ras-collection-instrument#39]
https://github.com/ONSdigital/ras-collection-instrument/blob/master/swagger_server/controllers/submitter/rabbitmq_submitter.py

The above module deals with publishing messages to a RabbitMQ cluster. Ideally, this should use the publisher confirms method of dealing with the broker, and that the AMQP RPC `immediate` bit is set to false and the `mandatory` bit is set to true.

When setup in this way, the AMQP server will return a `Basic.Ack` when a message is written to a master queue and all of its slave queues, allowing the publisher to retain a reference to the submitted data until it is confirmed as being on the queue.

**Comment by JamesGardiner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Collection instrument does not use the publisher confirms model for safe message transport](https://trello.com/c/M6VlovaG/9-collection-instrument-does-not-use-the-publisher-confirms-model-for-safe-message-transport)

**Comment by jcox-dev** [comment]
@JamesGardiner I expect we can close this now?
