### ISSUE TITLE
Application is not configured from its environment

### ISSUE THREAD

**Issue by JamesGardiner** [ONSdigital/ras-collection-instrument#60]
This service is currently configured via a config.yaml file: https://github.com/ONSdigital/ras-collection-instrument/blob/20cce0c57516e373adf4d3b67321f40e696a717a/app.py#L14

This is not 12FA compliant and is also different to our other Python microservices. For consistency and more streamlined deployment this service should take its configuration from its environment.

**Comment by JamesGardiner** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Make collection Instrument 12FA compliant](https://trello.com/c/aL4Mm2Cr/8-make-collection-instrument-12fa-compliant)

**Comment by emilioward** [comment]
Resolved now with latest PR
